language: node_js
node_js:
- lts/*
before_script:
- npm run build
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: YMTuGgmhsiiN6PEhv1oiSjus8LCG+ubkFhLNIhOiLT1l/ZfYL7pxwniO7WeazuF7xvGoPsACLngz/NkqbkhVzsjuqwkteqwkqCma1wAwIeUSLOuwTT1FGDsEXPQxClvZ1jvRXnUe/iLntmPaC+kOHgkWszNzizFYFdXmewggu00=
  on:
    tags: true
    repo: noflo/noflo-math
  skip_cleanup: true
